### ISSUE TITLE
cling failed to indentify name used in structured binding

### ISSUE THREAD

**Issue by NobodyXu** [root-project/cling#258] opened 2018-09-03 10:16 UTC
```
nobodyxu@debian:/usr/src/cling/tools/packaging/cling-build$ cling -std=c++17

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include <tuple>
[cling]$ auto [a, b] = std::tuple<int, char>(1, 'c');
[cling]$ a
input_line_5:2:2: error: use of undeclared identifier 'a'
 a
  ^
[cling]$ a;
input_line_6:2:2: error: use of undeclared identifier 'a'
 a;
  ^
[cling]$ #include <iostream>
[cling]$ std::cout << a;
input_line_8:2:15: error: use of undeclared identifier 'a'
 std::cout << a;
               ^
[cling]$ 
```

My cling is built using ```./cpt.py --create-dev-env Release --with-workdir=./cling-build/ --last-stable=pkg
``` from ```e0b472e46eb5861570497c2b9efabf96f2d4a485		tag 'cling-patches-rrelease_50' of http://root.cern.ch/git/llvm
```.

My machine is using `Debian 9.4` with `linux kernel 4.9.0-6-amd64`.

**Comment by ferdymercury** [comment] 2024-04-12 16:36
Dupe of https://github.com/root-project/cling/issues/193

**Closed by ferdymercury** 2024-04-12 16:36 UTC
