### ISSUE TITLE
Cannot use Cling due to failures in C++17 support, old version of LLVM being used

### ISSUE THREAD

**Issue by Yzrsah** [root-project/cling#276] opened 2018-12-10 19:20 UTC
I'd love to use Cling, but I cannot use it because it gives too many errors due to the old version of LLVM being used.

This old LLVM has various problems with C++17 support.

One of the main reasons I wanted to use Cling is to verify specific details about things *like* C++20.

I am using the Homebrew Cling on macOS: https://formulae.brew.sh/formula/cling

The Homebrew maintainers said they were unable to update Cling to LLVM 7 because of Cling's hard-coded built-in LLVM: https://github.com/Homebrew/homebrew-core/issues/33693

How can we get an updated cling on macOS?

**Comment by SimeonEhrig** [comment] 2019-06-06 06:33
The problem is that the Clang C++ API is really unstable. It takes some work to change the cling code to work with a new version of Clang/LLVM. But we also need a new version of the Clang/LLVM stack as we need support for new CUDA versions. So we would be really happy if the Clang/LLVM stack would be updated.

@Axel-Naumann Is there a plan to update the stack?

**Comment by Axel-Naumann** [comment] 2019-06-06 07:32
Thanks for the input - this does increase the priority for bumping the llvm version. I'll get back once we have a schedule.

**Comment by hahnjo** [comment] 2020-03-24 16:29
@Axel-Naumann what is the current status and future plans on updating LLVM? We would also be interested in getting rid of a few upstream bugs.

I did have a try myself and I think I got it working with LLVM 6 and from there at least partially with LLVM 7. As expected quite a few changes to updated APIs and so on. In other issues I saw a few references to an "ongoing" LLVM upgrade, so are you already tackling this at your end?

**Comment by Axel-Naumann** [comment] 2020-03-25 07:02
Thanks for your interest and offer to help! The upgrade is currently underway. Several issues need to be sorted out (e.g. a change in ownership in the JIT); I will report back here once it's in.

**Comment by hahnjo** [comment] 2020-03-25 07:45
> Thanks for your interest and offer to help! The upgrade is currently underway.

Perfect!

> Several issues need to be sorted out (e.g. a change in ownership in the JIT)

Yes, also came across that one. My "hack" was to create a copy via `llvm::CloneModule` before calling `addModule`, but I'm sure there is a better way.

What has bugged me more is that LLVM is much more lazy in emitting `GlobalValue`s. In particular this hits `inline` functions, `vtable`s and unreferenced `virtual` functions :-( I'll wait for your push so I can at least learn from the solution...

**Comment by jeaye** [comment] 2022-05-01 01:53
Hi! Just checking in to see the status of this and how any of us can help get cling updated to the latest LLVM release (14, I think).

**Comment by SimeonEhrig** [comment] 2022-05-02 07:15
Hi, @vgvassilev is mainly working on the current port to LLVM 13. This happens in the ROOT repository and will be automatically back ported to the cling repository, if it is merged in ROOT.

https://github.com/root-project/root/pull/10294

**Comment by ferdymercury** [comment] 2024-04-12 15:28
Current master is with LLVM16, pleas reopen if you still find an issue.

**Closed by ferdymercury** 2024-04-12 15:28 UTC
