### ISSUE TITLE
Structured binding doesn't work correctly.

### ISSUE THREAD

**Issue by hi60year** [root-project/cling#344] opened 2020-05-17 00:54 UTC
```
$cling -std=c++2a
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  g++-5  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20171010'
  Extraction of runtime standard library version was: '20200304'

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include <utility>
[cling]$ auto p = std::make_pair(2, "cpp")
(std::pair<int, const char *> &) { 2, "cpp" }
[cling]$ auto [a, b] = p
(std::pair<int, const char *> &) { 2, "cpp" }
[cling]$ a
input_line_7:2:2: error: use of undeclared identifier 'a'
 a
 ^
[cling]$ #include <iostream>
[cling]$ std::cout << a
input_line_9:2:15: error: use of undeclared identifier 'a'
 std::cout << a
              ^
[cling]$ 
```

**Comment by dpellegr** [comment] 2020-06-06 11:22
Not surprising given that cling is stuck to clang 5 and that full support to structured binding came with clang 8. See also: https://github.com/root-project/cling/issues/276

**Comment by hi60year** [comment] 2020-06-07 00:01
> Not surprising given that cling is stuck to clang 5 and that full support to structured binding came with [clang 8](https://clang.llvm.org/cxx_status.html). See also: #276

@dpellegr Thanks, I'll keep that in mind

**Comment by Axel-Naumann** [comment] 2020-06-07 10:16
This is a known limitation, we have a bug report open for it. It needs a bit more work than the (ongoing) llvm upgrade.

**Comment by ferdymercury** [comment] 2024-04-12 15:26
Current master leads to an assert:

`root.exe: /opt/root_src/interpreter/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:3350: void clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl): Assertion `VD->isFileVarDecl() && "Cannot emit local var decl as global."' failed.`

**Comment by ferdymercury** [comment] 2024-04-12 16:36
Dupe of https://github.com/root-project/cling/issues/193

**Closed by ferdymercury** 2024-04-12 16:36 UTC
