### ISSUE TITLE
Definition of Functions with Attributes Fails

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/cling#239] opened 2018-05-17 12:01 UTC
Definition of functions with `__attribute__` declarations outside of `rawInput` mode fail.

Both with CUDA `__global__` qualfiers and C++ attribute specifier sequences (eg. C++14 deprecated) we get:

```
cling -std=c++14

[cling]$ [[deprecated]] void bar(){}
// input_line_3:2:27: error: function definition is not allowed here

// works only in rawInput
[cling]$ .rawInput 1
[cling]! [[deprecated]] void foo(){}
[cling]! .rawInput 0
[cling]$ foo();
input_line_6:2:2: warning: 'foo' is deprecated [-Wdeprecated-declarations]
 foo();
 ^
input_line_5:1:3: note: 'foo' has been explicitly marked deprecated here
[[deprecated]] void foo(){}
```

**Comment by ax3l** [comment] 2018-05-24 11:50
cc @Axel-Naumann have you seen this before?
Especially cumbersome with modern C++ attributes but also makes CUDA code verbose.

**Comment by Axel-Naumann** [comment] 2018-05-24 14:51
We don't do attributes, generally :-) This is likely caused by lib/MetaProcessor/InputValidator.cpp not supporting annotations. It should totally be possible to add that. @SimeonEhrig mind giving it a shot?

**Comment by Axel-Naumann** [comment] 2018-05-24 15:35
Sorry - it's `cling::utils::getWrapPoint()` in lib/Utils/SourceNormalization.cpp!

**Comment by SimeonEhrig** [comment] 2018-06-18 13:57
I have developed a first solution and opened a Pull Request #246 . The Pull Request isn't ready to merge. I have just implemented a subset of functions, because I'm not sure, if have understand right the functionality of `cling::utils::getWrapPoint()` (maybe I implemented some "side effects" which avoid the detection of other c++ constructs). Could you please check my commit. If all fine, I will continue with the gnu attributes.

**Comment by ferdymercury** [comment] 2024-04-12 16:55
Seems fixed in current master.

**Closed by ferdymercury** 2024-04-12 16:55 UTC
Labels: bug
