### ISSUE TITLE
lambda: wrong behavior

### ISSUE THREAD

**Issue by gouarin** [root-project/cling#183] opened 2017-09-13 13:39 UTC
Hi, 

I'm playing with lambdas inside cling interpreter and there are some of wrong behaviors which I report in this issue.

```
[cling]$ int i;
[cling]$ auto lambda = [i](double x){return i*x;};
input_line_4:2:17: error: 'i' cannot be captured because it does not have automatic storage duration
 auto lambda = [i](double x){return i*x;};
                ^
input_line_3:2:6: note: 'i' declared here
 int i;
     ^
```

I think that the variable `i` is not in the same scope of `lambda` and this is why it doesn't work. But it is a correct C++ code.

Now, if I use the operator `=`

```
[cling]$ int i;
[cling]$ auto lambda = [=](double x){return i*x;};
[cling]$ lambda(3)
(double) 0.000000
[cling]$ i = 2
(int) 2
[cling]$ lambda(3)
(double) 6.000000
```

There is no error but it is normally a copy capture, so if I change the value of `i`, the second call of `lambda` must be unchanged.

If I write the same examples in a scope, it works as expected.

```
{
    int i = 0;
    auto lambda = [i](double x){return x*i;};
    std::cout << lambda(3) << "\n";
    i = 3;
    std::cout << lambda(3) << "\n";
}
```
**output**:
0
0

```
{
    int i = 0;
    auto lambda = [=](double x){return x*i;};
    std::cout << lambda(3) << "\n";
    i = 3;
    std::cout << lambda(3) << "\n";
}
```
**output**:
0
0

**Comment by Axel-Naumann** [comment] 2017-09-13 15:41
We actually had a detailed discussion on this - so by now I can say it's by design and I'm happy to hear your thoughts of it.

As you probably know, input on cling's prompt is wrapped into a function to be evaluated. That would make `int i` invisible - and thus it's actually pulled out of the function, onto the global scope.

Your lambda is thus referencing a global i, which does not have automatic storage duration. It fails just like this code:
```
// BAD.cxx
int i = 0;
auto lambda = [i](double x){return i*x;};
```
with
```
$ clang++ -std=c++11 -fsyntax-only BAD.cxx
BAD.cxx:3:16: error: 'i' cannot be captured because it does not have automatic storage duration
auto lambda = [i](double x){return i*x;};
               ^
BAD.cxx:2:5: note: 'i' declared here
int i = 0;
    ^
1 error generated.
```

If you enclose everything in a scope it won't be extracted from the function wrapper anymore, and `i` has indeed automatic storage duration.

Makes sense?

**Comment by gouarin** [comment] 2017-09-13 16:27
Tanks for your reply.

I understand why it doesn't work. I will begin a C++ course for students next week. The course and the practical sessions will be based on xeus-cling and so on cling. So, I think that I will report several bugs in the coming months.

Could you give me more informations about the discussion that you mentioned ? And do you have a roadmap or any plan to change the design ?

**Comment by Axel-Naumann** [comment] 2018-06-12 09:38
Sorry - we == cling dev team. If you can suggest a behavior that would be consistent with cling's "mental model" and would fix this case please let me know. I'll close it for now; I would call this behavior as "by design", even though I agree it's surprising.

**Closed by Axel-Naumann** 2018-06-12 09:38 UTC
